#!/bin/sh
EDITORCMD="gvim --servername '`basename "$1" .pdf`' --remote-silent '+%l<Enter>' %f"
# Highlight matched column
# EDITORCMD="gvim --servername '`basename "$1" .pdf`' --remote-silent '+%l<Enter>:match Search /\%%ll/' %f"


PDFFILE="$1"
if [ -f "$PDFFILE" ];then
	# danke an Feuerfieber
	# http://forum.ubuntuusers.de/topic/evince-synctex-vim-emacs-scite-lyx-kile-editor/#post-2841828
	if [ -f "${PDFFILE%%.pdf}.synctex.gz" ];then
		evince_backward_search "$PDFFILE" "$EDITORCMD"&
		BACKWARD_SEARCH_PID=$!
		echo $BACKWARD_SEARCH_PID
	fi
fi

/usr/bin/evince "$@"

if [ "$BACKWARD_SEARCH_PID" ];then
	echo "Killing $BACKWARD_SEARCH_PID"
	kill $BACKWARD_SEARCH_PID
fi
